name: Publish to TestPyPI and Sign with Sigstore

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "README.rst"

permissions:
  contents: read

jobs:
  build-wheel-package:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-build
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
          cache-dependency-path: |
            setup.py
            **/*requirements.txt
            tox.ini

      - run: make setup-ci

      - run: make build

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./dist/*

  publish-package:
    needs: build-wheel-package
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-publish-pkg
      cancel-in-progress: true
    timeout-minutes: 10
    environment:
      name: testpypi
      url: https://test.pypi.org/p/tcconfig
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

  sign-package:
    needs: publish-package
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref_name }}-sign-pkg
      cancel-in-progress: true
    timeout-minutes: 10
    permissions:
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Sign the dists with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - uses: actions/upload-artifact@v4
        with:
          name: sigstore
          path: ./dist/*
